modLoader="javafml"
loaderVersion="[36,)"
license="Academic Free License v3.0"

[[mods]]
modId="minecraftutilities"
version="1.0.0"
displayName="minecraftutilities"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Dominic, MCreator"

[[dependencies.minecraftutilities]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"

[[dependencies.minecraftutilities]]
    modId="forge"
    mandatory=true
    versionRange="[36.2.26]"
    ordering="NONE"
    side="BOTH"



