package net.mcreator.minecraftutilities;

import net.minecraftforge.fml.network.PacketDistributor;
import net.minecraftforge.fml.network.NetworkEvent;
import net.minecraftforge.fml.javafmlmod.FMLJavaModLoadingContext;
import net.minecraftforge.fml.event.lifecycle.FMLCommonSetupEvent;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.event.entity.player.PlayerEvent;
import net.minecraftforge.event.AttachCapabilitiesEvent;
import net.minecraftforge.common.util.LazyOptional;
import net.minecraftforge.common.util.FakePlayer;
import net.minecraftforge.common.capabilities.ICapabilitySerializable;
import net.minecraftforge.common.capabilities.CapabilityManager;
import net.minecraftforge.common.capabilities.CapabilityInject;
import net.minecraftforge.common.capabilities.Capability;

import net.minecraft.util.ResourceLocation;
import net.minecraft.util.Direction;
import net.minecraft.network.PacketBuffer;
import net.minecraft.nbt.INBT;
import net.minecraft.nbt.CompoundNBT;
import net.minecraft.item.ItemStack;
import net.minecraft.entity.player.ServerPlayerEntity;
import net.minecraft.entity.player.PlayerEntity;
import net.minecraft.entity.Entity;
import net.minecraft.client.Minecraft;

import java.util.function.Supplier;

public class MinecraftutilitiesModVariables {
	public MinecraftutilitiesModVariables(MinecraftutilitiesModElements elements) {
		elements.addNetworkMessage(PlayerVariablesSyncMessage.class, PlayerVariablesSyncMessage::buffer, PlayerVariablesSyncMessage::new,
				PlayerVariablesSyncMessage::handler);
		FMLJavaModLoadingContext.get().getModEventBus().addListener(this::init);
	}

	private void init(FMLCommonSetupEvent event) {
		CapabilityManager.INSTANCE.register(PlayerVariables.class, new PlayerVariablesStorage(), PlayerVariables::new);
	}

	@CapabilityInject(PlayerVariables.class)
	public static Capability<PlayerVariables> PLAYER_VARIABLES_CAPABILITY = null;

	@SubscribeEvent
	public void onAttachCapabilities(AttachCapabilitiesEvent<Entity> event) {
		if (event.getObject() instanceof PlayerEntity && !(event.getObject() instanceof FakePlayer))
			event.addCapability(new ResourceLocation("minecraftutilities", "player_variables"), new PlayerVariablesProvider());
	}

	private static class PlayerVariablesProvider implements ICapabilitySerializable<INBT> {
		private final LazyOptional<PlayerVariables> instance = LazyOptional.of(PLAYER_VARIABLES_CAPABILITY::getDefaultInstance);

		@Override
		public <T> LazyOptional<T> getCapability(Capability<T> cap, Direction side) {
			return cap == PLAYER_VARIABLES_CAPABILITY ? instance.cast() : LazyOptional.empty();
		}

		@Override
		public INBT serializeNBT() {
			return PLAYER_VARIABLES_CAPABILITY.getStorage().writeNBT(PLAYER_VARIABLES_CAPABILITY, this.instance.orElseThrow(RuntimeException::new),
					null);
		}

		@Override
		public void deserializeNBT(INBT nbt) {
			PLAYER_VARIABLES_CAPABILITY.getStorage().readNBT(PLAYER_VARIABLES_CAPABILITY, this.instance.orElseThrow(RuntimeException::new), null,
					nbt);
		}
	}

	private static class PlayerVariablesStorage implements Capability.IStorage<PlayerVariables> {
		@Override
		public INBT writeNBT(Capability<PlayerVariables> capability, PlayerVariables instance, Direction side) {
			CompoundNBT nbt = new CompoundNBT();
			nbt.put("itemSlot0", instance.itemSlot0.write(new CompoundNBT()));
			nbt.putDouble("itemSlot0quantity", instance.itemSlot0quantity);
			nbt.put("itemSlot1", instance.itemSlot1.write(new CompoundNBT()));
			nbt.putDouble("itemSlot1quantity", instance.itemSlot1quantity);
			nbt.put("itemSlot2", instance.itemSlot2.write(new CompoundNBT()));
			nbt.put("itemSlot3", instance.itemSlot3.write(new CompoundNBT()));
			nbt.put("itemSlot4", instance.itemSlot4.write(new CompoundNBT()));
			nbt.put("itemSlot5", instance.itemSlot5.write(new CompoundNBT()));
			nbt.put("itemSlot6", instance.itemSlot6.write(new CompoundNBT()));
			nbt.put("itemSlot7", instance.itemSlot7.write(new CompoundNBT()));
			nbt.put("itemSlot8", instance.itemSlot8.write(new CompoundNBT()));
			nbt.put("itemSlot9", instance.itemSlot9.write(new CompoundNBT()));
			nbt.put("itemSlot10", instance.itemSlot10.write(new CompoundNBT()));
			nbt.put("itemSlot11", instance.itemSlot11.write(new CompoundNBT()));
			nbt.put("itemSlot12", instance.itemSlot12.write(new CompoundNBT()));
			nbt.put("itemSlot13", instance.itemSlot13.write(new CompoundNBT()));
			nbt.put("itemSlot14", instance.itemSlot14.write(new CompoundNBT()));
			nbt.put("itemSlot15", instance.itemSlot15.write(new CompoundNBT()));
			nbt.put("itemSlot16", instance.itemSlot16.write(new CompoundNBT()));
			nbt.put("itemSlot17", instance.itemSlot17.write(new CompoundNBT()));
			nbt.put("itemSlot18", instance.itemSlot18.write(new CompoundNBT()));
			nbt.put("itemSlot19", instance.itemSlot19.write(new CompoundNBT()));
			nbt.put("itemSlot20", instance.itemSlot20.write(new CompoundNBT()));
			nbt.put("itemSlot21", instance.itemSlot21.write(new CompoundNBT()));
			nbt.put("itemSlot22", instance.itemSlot22.write(new CompoundNBT()));
			nbt.put("itemSlot23", instance.itemSlot23.write(new CompoundNBT()));
			nbt.put("itemSlot24", instance.itemSlot24.write(new CompoundNBT()));
			nbt.put("itemSlot25", instance.itemSlot25.write(new CompoundNBT()));
			nbt.put("itemSlot26", instance.itemSlot26.write(new CompoundNBT()));
			nbt.put("itemSlot27", instance.itemSlot27.write(new CompoundNBT()));
			nbt.put("itemSlot28", instance.itemSlot28.write(new CompoundNBT()));
			nbt.put("itemSlot29", instance.itemSlot29.write(new CompoundNBT()));
			nbt.put("itemSlot30", instance.itemSlot30.write(new CompoundNBT()));
			nbt.put("itemSlot31", instance.itemSlot31.write(new CompoundNBT()));
			nbt.put("itemSlot32", instance.itemSlot32.write(new CompoundNBT()));
			nbt.put("itemSlot33", instance.itemSlot33.write(new CompoundNBT()));
			nbt.put("itemSlot34", instance.itemSlot34.write(new CompoundNBT()));
			nbt.put("itemSlot35", instance.itemSlot35.write(new CompoundNBT()));
			nbt.put("itemSlot36", instance.itemSlot36.write(new CompoundNBT()));
			nbt.put("itemSlot37", instance.itemSlot37.write(new CompoundNBT()));
			nbt.put("itemSlot38", instance.itemSlot38.write(new CompoundNBT()));
			nbt.put("itemSlot39", instance.itemSlot39.write(new CompoundNBT()));
			nbt.put("itemSlot40", instance.itemSlot40.write(new CompoundNBT()));
			nbt.put("itemSlot41", instance.itemSlot41.write(new CompoundNBT()));
			nbt.put("itemSlot42", instance.itemSlot42.write(new CompoundNBT()));
			nbt.put("itemSlot43", instance.itemSlot43.write(new CompoundNBT()));
			nbt.put("itemSlot44", instance.itemSlot44.write(new CompoundNBT()));
			nbt.put("itemSlot45", instance.itemSlot45.write(new CompoundNBT()));
			nbt.put("itemSlot46", instance.itemSlot46.write(new CompoundNBT()));
			nbt.put("itemSlot47", instance.itemSlot47.write(new CompoundNBT()));
			nbt.put("itemSlot48", instance.itemSlot48.write(new CompoundNBT()));
			nbt.put("itemSlot49", instance.itemSlot49.write(new CompoundNBT()));
			nbt.put("itemSlot50", instance.itemSlot50.write(new CompoundNBT()));
			nbt.put("itemSlot51", instance.itemSlot51.write(new CompoundNBT()));
			nbt.put("itemSlot52", instance.itemSlot52.write(new CompoundNBT()));
			nbt.put("itemSlot53", instance.itemSlot53.write(new CompoundNBT()));
			nbt.put("itemSlot54", instance.itemSlot54.write(new CompoundNBT()));
			nbt.put("itemSlot55", instance.itemSlot55.write(new CompoundNBT()));
			nbt.put("itemSlot56", instance.itemSlot56.write(new CompoundNBT()));
			nbt.put("itemSlot57", instance.itemSlot57.write(new CompoundNBT()));
			nbt.put("itemSlot58", instance.itemSlot58.write(new CompoundNBT()));
			nbt.put("itemSlot59", instance.itemSlot59.write(new CompoundNBT()));
			nbt.put("itemSlot60", instance.itemSlot60.write(new CompoundNBT()));
			nbt.put("itemSlot61", instance.itemSlot61.write(new CompoundNBT()));
			nbt.put("itemSlot62", instance.itemSlot62.write(new CompoundNBT()));
			nbt.put("itemSlot63", instance.itemSlot63.write(new CompoundNBT()));
			nbt.put("itemSlot64", instance.itemSlot64.write(new CompoundNBT()));
			nbt.put("itemSlot65", instance.itemSlot65.write(new CompoundNBT()));
			nbt.put("itemSlot66", instance.itemSlot66.write(new CompoundNBT()));
			nbt.put("itemSlot67", instance.itemSlot67.write(new CompoundNBT()));
			nbt.put("itemSlot68", instance.itemSlot68.write(new CompoundNBT()));
			nbt.put("itemSlot69", instance.itemSlot69.write(new CompoundNBT()));
			nbt.put("itemSlot70", instance.itemSlot70.write(new CompoundNBT()));
			nbt.put("itemSlot71", instance.itemSlot71.write(new CompoundNBT()));
			nbt.put("itemSlot72", instance.itemSlot72.write(new CompoundNBT()));
			nbt.put("itemSlot73", instance.itemSlot73.write(new CompoundNBT()));
			nbt.put("itemSlot74", instance.itemSlot74.write(new CompoundNBT()));
			nbt.put("itemSlot75", instance.itemSlot75.write(new CompoundNBT()));
			nbt.put("itemSlot77", instance.itemSlot77.write(new CompoundNBT()));
			nbt.put("itemSlot78", instance.itemSlot78.write(new CompoundNBT()));
			nbt.put("itemSlot79", instance.itemSlot79.write(new CompoundNBT()));
			nbt.put("itemSlot80", instance.itemSlot80.write(new CompoundNBT()));
			nbt.put("itemSlot81", instance.itemSlot81.write(new CompoundNBT()));
			nbt.put("itemSlot82", instance.itemSlot82.write(new CompoundNBT()));
			nbt.put("itemSlot83", instance.itemSlot83.write(new CompoundNBT()));
			nbt.put("itemSlot84", instance.itemSlot84.write(new CompoundNBT()));
			nbt.put("itemSlot85", instance.itemSlot85.write(new CompoundNBT()));
			nbt.put("itemSlot86", instance.itemSlot86.write(new CompoundNBT()));
			nbt.put("itemSlot87", instance.itemSlot87.write(new CompoundNBT()));
			nbt.put("itemSlot88", instance.itemSlot88.write(new CompoundNBT()));
			nbt.put("itemSlot89", instance.itemSlot89.write(new CompoundNBT()));
			nbt.put("itemSlot91", instance.itemSlot91.write(new CompoundNBT()));
			nbt.put("itemSlot92", instance.itemSlot92.write(new CompoundNBT()));
			nbt.put("itemSlot93", instance.itemSlot93.write(new CompoundNBT()));
			nbt.put("itemSlot94", instance.itemSlot94.write(new CompoundNBT()));
			nbt.put("itemSlot95", instance.itemSlot95.write(new CompoundNBT()));
			nbt.put("itemSlot96", instance.itemSlot96.write(new CompoundNBT()));
			nbt.put("itemSlot97", instance.itemSlot97.write(new CompoundNBT()));
			nbt.put("itemSlot98", instance.itemSlot98.write(new CompoundNBT()));
			nbt.put("itemSlot99", instance.itemSlot99.write(new CompoundNBT()));
			nbt.put("itemSlot100", instance.itemSlot100.write(new CompoundNBT()));
			nbt.put("itemSlot101", instance.itemSlot101.write(new CompoundNBT()));
			nbt.put("itemSlot102", instance.itemSlot102.write(new CompoundNBT()));
			nbt.put("itemSlot103", instance.itemSlot103.write(new CompoundNBT()));
			nbt.put("itemSlot104", instance.itemSlot104.write(new CompoundNBT()));
			nbt.put("itemSlot105", instance.itemSlot105.write(new CompoundNBT()));
			nbt.put("itemSlot106", instance.itemSlot106.write(new CompoundNBT()));
			nbt.put("itemSlot107", instance.itemSlot107.write(new CompoundNBT()));
			nbt.put("itemSlot108", instance.itemSlot108.write(new CompoundNBT()));
			nbt.put("itemSlot109", instance.itemSlot109.write(new CompoundNBT()));
			nbt.put("itemSlot110", instance.itemSlot110.write(new CompoundNBT()));
			nbt.put("itemSlot111", instance.itemSlot111.write(new CompoundNBT()));
			nbt.put("itemSlot112", instance.itemSlot112.write(new CompoundNBT()));
			nbt.put("itemSlot113", instance.itemSlot113.write(new CompoundNBT()));
			nbt.put("itemSlot114", instance.itemSlot114.write(new CompoundNBT()));
			nbt.put("itemSlot115", instance.itemSlot115.write(new CompoundNBT()));
			nbt.put("itemSlot116", instance.itemSlot116.write(new CompoundNBT()));
			nbt.put("itemSlot117", instance.itemSlot117.write(new CompoundNBT()));
			nbt.put("itemSlot118", instance.itemSlot118.write(new CompoundNBT()));
			nbt.put("itemSlot119", instance.itemSlot119.write(new CompoundNBT()));
			nbt.put("itemSlot120", instance.itemSlot120.write(new CompoundNBT()));
			nbt.put("itemSlot121", instance.itemSlot121.write(new CompoundNBT()));
			nbt.put("itemSlot122", instance.itemSlot122.write(new CompoundNBT()));
			nbt.put("itemSlot123", instance.itemSlot123.write(new CompoundNBT()));
			nbt.put("itemSlot124", instance.itemSlot124.write(new CompoundNBT()));
			nbt.put("itemSlot125", instance.itemSlot125.write(new CompoundNBT()));
			nbt.put("itemSlot126", instance.itemSlot126.write(new CompoundNBT()));
			nbt.put("itemSlot127", instance.itemSlot127.write(new CompoundNBT()));
			nbt.put("itemSlot128", instance.itemSlot128.write(new CompoundNBT()));
			nbt.put("itemSlot129", instance.itemSlot129.write(new CompoundNBT()));
			nbt.put("itemSlot130", instance.itemSlot130.write(new CompoundNBT()));
			nbt.put("itemSlot131", instance.itemSlot131.write(new CompoundNBT()));
			nbt.put("itemSlot132", instance.itemSlot132.write(new CompoundNBT()));
			nbt.put("itemSlot133", instance.itemSlot133.write(new CompoundNBT()));
			nbt.put("itemSlot134", instance.itemSlot134.write(new CompoundNBT()));
			nbt.put("itemSlot135", instance.itemSlot135.write(new CompoundNBT()));
			nbt.put("itemSlot136", instance.itemSlot136.write(new CompoundNBT()));
			nbt.put("itemSlot137", instance.itemSlot137.write(new CompoundNBT()));
			nbt.put("itemSlot138", instance.itemSlot138.write(new CompoundNBT()));
			nbt.put("itemSlot139", instance.itemSlot139.write(new CompoundNBT()));
			nbt.put("itemSlot140", instance.itemSlot140.write(new CompoundNBT()));
			nbt.put("itemSlot141", instance.itemSlot141.write(new CompoundNBT()));
			nbt.put("itemSlot142", instance.itemSlot142.write(new CompoundNBT()));
			nbt.put("itemSlot143", instance.itemSlot143.write(new CompoundNBT()));
			nbt.put("itemSlot144", instance.itemSlot144.write(new CompoundNBT()));
			nbt.put("itemSlot145", instance.itemSlot145.write(new CompoundNBT()));
			nbt.put("itemSlot146", instance.itemSlot146.write(new CompoundNBT()));
			nbt.put("itemSlot147", instance.itemSlot147.write(new CompoundNBT()));
			nbt.put("itemSlot148", instance.itemSlot148.write(new CompoundNBT()));
			nbt.put("itemSlot149", instance.itemSlot149.write(new CompoundNBT()));
			nbt.put("itemSlot150", instance.itemSlot150.write(new CompoundNBT()));
			nbt.put("itemSlot151", instance.itemSlot151.write(new CompoundNBT()));
			nbt.put("itemSlot152", instance.itemSlot152.write(new CompoundNBT()));
			nbt.put("itemSlot153", instance.itemSlot153.write(new CompoundNBT()));
			nbt.put("itemSlot154", instance.itemSlot154.write(new CompoundNBT()));
			nbt.put("itemSlot155", instance.itemSlot155.write(new CompoundNBT()));
			nbt.put("itemSlot156", instance.itemSlot156.write(new CompoundNBT()));
			nbt.put("itemSlot157", instance.itemSlot157.write(new CompoundNBT()));
			nbt.put("itemSlot158", instance.itemSlot158.write(new CompoundNBT()));
			nbt.put("itemSlot159", instance.itemSlot159.write(new CompoundNBT()));
			nbt.put("itemSlot160", instance.itemSlot160.write(new CompoundNBT()));
			nbt.put("itemSlot161", instance.itemSlot161.write(new CompoundNBT()));
			nbt.put("itemSlot162", instance.itemSlot162.write(new CompoundNBT()));
			nbt.put("itemSlot163", instance.itemSlot163.write(new CompoundNBT()));
			nbt.put("itemSlot164", instance.itemSlot164.write(new CompoundNBT()));
			nbt.put("itemSlot165", instance.itemSlot165.write(new CompoundNBT()));
			nbt.put("itemSlot166", instance.itemSlot166.write(new CompoundNBT()));
			nbt.put("itemSlot167", instance.itemSlot167.write(new CompoundNBT()));
			nbt.put("itemSlot168", instance.itemSlot168.write(new CompoundNBT()));
			nbt.put("itemSlot169", instance.itemSlot169.write(new CompoundNBT()));
			nbt.put("itemSlot170", instance.itemSlot170.write(new CompoundNBT()));
			nbt.put("itemSlot171", instance.itemSlot171.write(new CompoundNBT()));
			nbt.put("itemSlot172", instance.itemSlot172.write(new CompoundNBT()));
			nbt.put("itemSlot173", instance.itemSlot173.write(new CompoundNBT()));
			nbt.put("itemSlot174", instance.itemSlot174.write(new CompoundNBT()));
			nbt.put("itemSlot175", instance.itemSlot175.write(new CompoundNBT()));
			nbt.put("itemSlot176", instance.itemSlot176.write(new CompoundNBT()));
			nbt.put("itemSlot177", instance.itemSlot177.write(new CompoundNBT()));
			nbt.put("itemSlot178", instance.itemSlot178.write(new CompoundNBT()));
			nbt.put("itemSlot179", instance.itemSlot179.write(new CompoundNBT()));
			nbt.put("itemSlot180", instance.itemSlot180.write(new CompoundNBT()));
			nbt.put("itemSlot181", instance.itemSlot181.write(new CompoundNBT()));
			nbt.put("itemSlot182", instance.itemSlot182.write(new CompoundNBT()));
			nbt.put("itemSlot183", instance.itemSlot183.write(new CompoundNBT()));
			nbt.put("itemSlot184", instance.itemSlot184.write(new CompoundNBT()));
			nbt.put("itemSlot185", instance.itemSlot185.write(new CompoundNBT()));
			nbt.put("itemSlot186", instance.itemSlot186.write(new CompoundNBT()));
			nbt.put("itemSlot187", instance.itemSlot187.write(new CompoundNBT()));
			nbt.put("itemSlot188", instance.itemSlot188.write(new CompoundNBT()));
			nbt.put("itemSlot189", instance.itemSlot189.write(new CompoundNBT()));
			nbt.put("itemSlot190", instance.itemSlot190.write(new CompoundNBT()));
			nbt.put("itemSlot191", instance.itemSlot191.write(new CompoundNBT()));
			nbt.put("itemSlot192", instance.itemSlot192.write(new CompoundNBT()));
			nbt.put("itemSlot193", instance.itemSlot193.write(new CompoundNBT()));
			nbt.put("itemSlot194", instance.itemSlot194.write(new CompoundNBT()));
			nbt.put("itemSlot195", instance.itemSlot195.write(new CompoundNBT()));
			nbt.put("itemSlot196", instance.itemSlot196.write(new CompoundNBT()));
			nbt.put("itemSlot197", instance.itemSlot197.write(new CompoundNBT()));
			nbt.put("itemSlot198", instance.itemSlot198.write(new CompoundNBT()));
			nbt.put("itemSlot199", instance.itemSlot199.write(new CompoundNBT()));
			nbt.put("itemSlot200", instance.itemSlot200.write(new CompoundNBT()));
			nbt.put("itemSlot201", instance.itemSlot201.write(new CompoundNBT()));
			nbt.put("itemSlot202", instance.itemSlot202.write(new CompoundNBT()));
			nbt.put("itemSlot203", instance.itemSlot203.write(new CompoundNBT()));
			nbt.put("itemSlot204", instance.itemSlot204.write(new CompoundNBT()));
			nbt.put("itemSlot205", instance.itemSlot205.write(new CompoundNBT()));
			nbt.put("itemSlot206", instance.itemSlot206.write(new CompoundNBT()));
			nbt.put("itemSlot207", instance.itemSlot207.write(new CompoundNBT()));
			nbt.put("itemSlot208", instance.itemSlot208.write(new CompoundNBT()));
			nbt.put("itemSlot209", instance.itemSlot209.write(new CompoundNBT()));
			nbt.put("itemSlot210", instance.itemSlot210.write(new CompoundNBT()));
			nbt.put("itemSlot211", instance.itemSlot211.write(new CompoundNBT()));
			nbt.put("itemSlot212", instance.itemSlot212.write(new CompoundNBT()));
			nbt.put("itemSlot213", instance.itemSlot213.write(new CompoundNBT()));
			nbt.put("itemSlot214", instance.itemSlot214.write(new CompoundNBT()));
			nbt.put("itemSlot215", instance.itemSlot215.write(new CompoundNBT()));
			nbt.put("itemSlot216", instance.itemSlot216.write(new CompoundNBT()));
			nbt.put("itemSlot217", instance.itemSlot217.write(new CompoundNBT()));
			nbt.put("itemSlot219", instance.itemSlot219.write(new CompoundNBT()));
			nbt.put("itemSlot220", instance.itemSlot220.write(new CompoundNBT()));
			nbt.put("itemSlot221", instance.itemSlot221.write(new CompoundNBT()));
			nbt.put("itemSlot222", instance.itemSlot222.write(new CompoundNBT()));
			nbt.put("itemSlot223", instance.itemSlot223.write(new CompoundNBT()));
			nbt.put("itemSlot218", instance.itemSlot218.write(new CompoundNBT()));
			nbt.put("itemSlot224", instance.itemSlot224.write(new CompoundNBT()));
			nbt.put("itemSlot225", instance.itemSlot225.write(new CompoundNBT()));
			nbt.put("itemSlot226", instance.itemSlot226.write(new CompoundNBT()));
			nbt.put("itemSlot227", instance.itemSlot227.write(new CompoundNBT()));
			nbt.put("itemSlot228", instance.itemSlot228.write(new CompoundNBT()));
			nbt.put("itemSlot229", instance.itemSlot229.write(new CompoundNBT()));
			nbt.put("itemSlot230", instance.itemSlot230.write(new CompoundNBT()));
			nbt.put("itemSlot231", instance.itemSlot231.write(new CompoundNBT()));
			nbt.put("itemSlot232", instance.itemSlot232.write(new CompoundNBT()));
			nbt.put("itemSlot233", instance.itemSlot233.write(new CompoundNBT()));
			nbt.put("itemSlot234", instance.itemSlot234.write(new CompoundNBT()));
			nbt.put("itemSlot235", instance.itemSlot235.write(new CompoundNBT()));
			nbt.put("itemSlot236", instance.itemSlot236.write(new CompoundNBT()));
			nbt.put("itemSlot237", instance.itemSlot237.write(new CompoundNBT()));
			nbt.put("itemSlot238", instance.itemSlot238.write(new CompoundNBT()));
			nbt.put("itemSlot239", instance.itemSlot239.write(new CompoundNBT()));
			nbt.put("itemSlot241", instance.itemSlot241.write(new CompoundNBT()));
			nbt.put("itemSlot240", instance.itemSlot240.write(new CompoundNBT()));
			nbt.put("itemSlot242", instance.itemSlot242.write(new CompoundNBT()));
			nbt.put("itemSlot243", instance.itemSlot243.write(new CompoundNBT()));
			nbt.put("itemSlot244", instance.itemSlot244.write(new CompoundNBT()));
			nbt.put("itemSlot245", instance.itemSlot245.write(new CompoundNBT()));
			return nbt;
		}

		@Override
		public void readNBT(Capability<PlayerVariables> capability, PlayerVariables instance, Direction side, INBT inbt) {
			CompoundNBT nbt = (CompoundNBT) inbt;
			instance.itemSlot0 = ItemStack.read(nbt.getCompound("itemSlot0"));
			instance.itemSlot0quantity = nbt.getDouble("itemSlot0quantity");
			instance.itemSlot1 = ItemStack.read(nbt.getCompound("itemSlot1"));
			instance.itemSlot1quantity = nbt.getDouble("itemSlot1quantity");
			instance.itemSlot2 = ItemStack.read(nbt.getCompound("itemSlot2"));
			instance.itemSlot3 = ItemStack.read(nbt.getCompound("itemSlot3"));
			instance.itemSlot4 = ItemStack.read(nbt.getCompound("itemSlot4"));
			instance.itemSlot5 = ItemStack.read(nbt.getCompound("itemSlot5"));
			instance.itemSlot6 = ItemStack.read(nbt.getCompound("itemSlot6"));
			instance.itemSlot7 = ItemStack.read(nbt.getCompound("itemSlot7"));
			instance.itemSlot8 = ItemStack.read(nbt.getCompound("itemSlot8"));
			instance.itemSlot9 = ItemStack.read(nbt.getCompound("itemSlot9"));
			instance.itemSlot10 = ItemStack.read(nbt.getCompound("itemSlot10"));
			instance.itemSlot11 = ItemStack.read(nbt.getCompound("itemSlot11"));
			instance.itemSlot12 = ItemStack.read(nbt.getCompound("itemSlot12"));
			instance.itemSlot13 = ItemStack.read(nbt.getCompound("itemSlot13"));
			instance.itemSlot14 = ItemStack.read(nbt.getCompound("itemSlot14"));
			instance.itemSlot15 = ItemStack.read(nbt.getCompound("itemSlot15"));
			instance.itemSlot16 = ItemStack.read(nbt.getCompound("itemSlot16"));
			instance.itemSlot17 = ItemStack.read(nbt.getCompound("itemSlot17"));
			instance.itemSlot18 = ItemStack.read(nbt.getCompound("itemSlot18"));
			instance.itemSlot19 = ItemStack.read(nbt.getCompound("itemSlot19"));
			instance.itemSlot20 = ItemStack.read(nbt.getCompound("itemSlot20"));
			instance.itemSlot21 = ItemStack.read(nbt.getCompound("itemSlot21"));
			instance.itemSlot22 = ItemStack.read(nbt.getCompound("itemSlot22"));
			instance.itemSlot23 = ItemStack.read(nbt.getCompound("itemSlot23"));
			instance.itemSlot24 = ItemStack.read(nbt.getCompound("itemSlot24"));
			instance.itemSlot25 = ItemStack.read(nbt.getCompound("itemSlot25"));
			instance.itemSlot26 = ItemStack.read(nbt.getCompound("itemSlot26"));
			instance.itemSlot27 = ItemStack.read(nbt.getCompound("itemSlot27"));
			instance.itemSlot28 = ItemStack.read(nbt.getCompound("itemSlot28"));
			instance.itemSlot29 = ItemStack.read(nbt.getCompound("itemSlot29"));
			instance.itemSlot30 = ItemStack.read(nbt.getCompound("itemSlot30"));
			instance.itemSlot31 = ItemStack.read(nbt.getCompound("itemSlot31"));
			instance.itemSlot32 = ItemStack.read(nbt.getCompound("itemSlot32"));
			instance.itemSlot33 = ItemStack.read(nbt.getCompound("itemSlot33"));
			instance.itemSlot34 = ItemStack.read(nbt.getCompound("itemSlot34"));
			instance.itemSlot35 = ItemStack.read(nbt.getCompound("itemSlot35"));
			instance.itemSlot36 = ItemStack.read(nbt.getCompound("itemSlot36"));
			instance.itemSlot37 = ItemStack.read(nbt.getCompound("itemSlot37"));
			instance.itemSlot38 = ItemStack.read(nbt.getCompound("itemSlot38"));
			instance.itemSlot39 = ItemStack.read(nbt.getCompound("itemSlot39"));
			instance.itemSlot40 = ItemStack.read(nbt.getCompound("itemSlot40"));
			instance.itemSlot41 = ItemStack.read(nbt.getCompound("itemSlot41"));
			instance.itemSlot42 = ItemStack.read(nbt.getCompound("itemSlot42"));
			instance.itemSlot43 = ItemStack.read(nbt.getCompound("itemSlot43"));
			instance.itemSlot44 = ItemStack.read(nbt.getCompound("itemSlot44"));
			instance.itemSlot45 = ItemStack.read(nbt.getCompound("itemSlot45"));
			instance.itemSlot46 = ItemStack.read(nbt.getCompound("itemSlot46"));
			instance.itemSlot47 = ItemStack.read(nbt.getCompound("itemSlot47"));
			instance.itemSlot48 = ItemStack.read(nbt.getCompound("itemSlot48"));
			instance.itemSlot49 = ItemStack.read(nbt.getCompound("itemSlot49"));
			instance.itemSlot50 = ItemStack.read(nbt.getCompound("itemSlot50"));
			instance.itemSlot51 = ItemStack.read(nbt.getCompound("itemSlot51"));
			instance.itemSlot52 = ItemStack.read(nbt.getCompound("itemSlot52"));
			instance.itemSlot53 = ItemStack.read(nbt.getCompound("itemSlot53"));
			instance.itemSlot54 = ItemStack.read(nbt.getCompound("itemSlot54"));
			instance.itemSlot55 = ItemStack.read(nbt.getCompound("itemSlot55"));
			instance.itemSlot56 = ItemStack.read(nbt.getCompound("itemSlot56"));
			instance.itemSlot57 = ItemStack.read(nbt.getCompound("itemSlot57"));
			instance.itemSlot58 = ItemStack.read(nbt.getCompound("itemSlot58"));
			instance.itemSlot59 = ItemStack.read(nbt.getCompound("itemSlot59"));
			instance.itemSlot60 = ItemStack.read(nbt.getCompound("itemSlot60"));
			instance.itemSlot61 = ItemStack.read(nbt.getCompound("itemSlot61"));
			instance.itemSlot62 = ItemStack.read(nbt.getCompound("itemSlot62"));
			instance.itemSlot63 = ItemStack.read(nbt.getCompound("itemSlot63"));
			instance.itemSlot64 = ItemStack.read(nbt.getCompound("itemSlot64"));
			instance.itemSlot65 = ItemStack.read(nbt.getCompound("itemSlot65"));
			instance.itemSlot66 = ItemStack.read(nbt.getCompound("itemSlot66"));
			instance.itemSlot67 = ItemStack.read(nbt.getCompound("itemSlot67"));
			instance.itemSlot68 = ItemStack.read(nbt.getCompound("itemSlot68"));
			instance.itemSlot69 = ItemStack.read(nbt.getCompound("itemSlot69"));
			instance.itemSlot70 = ItemStack.read(nbt.getCompound("itemSlot70"));
			instance.itemSlot71 = ItemStack.read(nbt.getCompound("itemSlot71"));
			instance.itemSlot72 = ItemStack.read(nbt.getCompound("itemSlot72"));
			instance.itemSlot73 = ItemStack.read(nbt.getCompound("itemSlot73"));
			instance.itemSlot74 = ItemStack.read(nbt.getCompound("itemSlot74"));
			instance.itemSlot75 = ItemStack.read(nbt.getCompound("itemSlot75"));
			instance.itemSlot77 = ItemStack.read(nbt.getCompound("itemSlot77"));
			instance.itemSlot78 = ItemStack.read(nbt.getCompound("itemSlot78"));
			instance.itemSlot79 = ItemStack.read(nbt.getCompound("itemSlot79"));
			instance.itemSlot80 = ItemStack.read(nbt.getCompound("itemSlot80"));
			instance.itemSlot81 = ItemStack.read(nbt.getCompound("itemSlot81"));
			instance.itemSlot82 = ItemStack.read(nbt.getCompound("itemSlot82"));
			instance.itemSlot83 = ItemStack.read(nbt.getCompound("itemSlot83"));
			instance.itemSlot84 = ItemStack.read(nbt.getCompound("itemSlot84"));
			instance.itemSlot85 = ItemStack.read(nbt.getCompound("itemSlot85"));
			instance.itemSlot86 = ItemStack.read(nbt.getCompound("itemSlot86"));
			instance.itemSlot87 = ItemStack.read(nbt.getCompound("itemSlot87"));
			instance.itemSlot88 = ItemStack.read(nbt.getCompound("itemSlot88"));
			instance.itemSlot89 = ItemStack.read(nbt.getCompound("itemSlot89"));
			instance.itemSlot91 = ItemStack.read(nbt.getCompound("itemSlot91"));
			instance.itemSlot92 = ItemStack.read(nbt.getCompound("itemSlot92"));
			instance.itemSlot93 = ItemStack.read(nbt.getCompound("itemSlot93"));
			instance.itemSlot94 = ItemStack.read(nbt.getCompound("itemSlot94"));
			instance.itemSlot95 = ItemStack.read(nbt.getCompound("itemSlot95"));
			instance.itemSlot96 = ItemStack.read(nbt.getCompound("itemSlot96"));
			instance.itemSlot97 = ItemStack.read(nbt.getCompound("itemSlot97"));
			instance.itemSlot98 = ItemStack.read(nbt.getCompound("itemSlot98"));
			instance.itemSlot99 = ItemStack.read(nbt.getCompound("itemSlot99"));
			instance.itemSlot100 = ItemStack.read(nbt.getCompound("itemSlot100"));
			instance.itemSlot101 = ItemStack.read(nbt.getCompound("itemSlot101"));
			instance.itemSlot102 = ItemStack.read(nbt.getCompound("itemSlot102"));
			instance.itemSlot103 = ItemStack.read(nbt.getCompound("itemSlot103"));
			instance.itemSlot104 = ItemStack.read(nbt.getCompound("itemSlot104"));
			instance.itemSlot105 = ItemStack.read(nbt.getCompound("itemSlot105"));
			instance.itemSlot106 = ItemStack.read(nbt.getCompound("itemSlot106"));
			instance.itemSlot107 = ItemStack.read(nbt.getCompound("itemSlot107"));
			instance.itemSlot108 = ItemStack.read(nbt.getCompound("itemSlot108"));
			instance.itemSlot109 = ItemStack.read(nbt.getCompound("itemSlot109"));
			instance.itemSlot110 = ItemStack.read(nbt.getCompound("itemSlot110"));
			instance.itemSlot111 = ItemStack.read(nbt.getCompound("itemSlot111"));
			instance.itemSlot112 = ItemStack.read(nbt.getCompound("itemSlot112"));
			instance.itemSlot113 = ItemStack.read(nbt.getCompound("itemSlot113"));
			instance.itemSlot114 = ItemStack.read(nbt.getCompound("itemSlot114"));
			instance.itemSlot115 = ItemStack.read(nbt.getCompound("itemSlot115"));
			instance.itemSlot116 = ItemStack.read(nbt.getCompound("itemSlot116"));
			instance.itemSlot117 = ItemStack.read(nbt.getCompound("itemSlot117"));
			instance.itemSlot118 = ItemStack.read(nbt.getCompound("itemSlot118"));
			instance.itemSlot119 = ItemStack.read(nbt.getCompound("itemSlot119"));
			instance.itemSlot120 = ItemStack.read(nbt.getCompound("itemSlot120"));
			instance.itemSlot121 = ItemStack.read(nbt.getCompound("itemSlot121"));
			instance.itemSlot122 = ItemStack.read(nbt.getCompound("itemSlot122"));
			instance.itemSlot123 = ItemStack.read(nbt.getCompound("itemSlot123"));
			instance.itemSlot124 = ItemStack.read(nbt.getCompound("itemSlot124"));
			instance.itemSlot125 = ItemStack.read(nbt.getCompound("itemSlot125"));
			instance.itemSlot126 = ItemStack.read(nbt.getCompound("itemSlot126"));
			instance.itemSlot127 = ItemStack.read(nbt.getCompound("itemSlot127"));
			instance.itemSlot128 = ItemStack.read(nbt.getCompound("itemSlot128"));
			instance.itemSlot129 = ItemStack.read(nbt.getCompound("itemSlot129"));
			instance.itemSlot130 = ItemStack.read(nbt.getCompound("itemSlot130"));
			instance.itemSlot131 = ItemStack.read(nbt.getCompound("itemSlot131"));
			instance.itemSlot132 = ItemStack.read(nbt.getCompound("itemSlot132"));
			instance.itemSlot133 = ItemStack.read(nbt.getCompound("itemSlot133"));
			instance.itemSlot134 = ItemStack.read(nbt.getCompound("itemSlot134"));
			instance.itemSlot135 = ItemStack.read(nbt.getCompound("itemSlot135"));
			instance.itemSlot136 = ItemStack.read(nbt.getCompound("itemSlot136"));
			instance.itemSlot137 = ItemStack.read(nbt.getCompound("itemSlot137"));
			instance.itemSlot138 = ItemStack.read(nbt.getCompound("itemSlot138"));
			instance.itemSlot139 = ItemStack.read(nbt.getCompound("itemSlot139"));
			instance.itemSlot140 = ItemStack.read(nbt.getCompound("itemSlot140"));
			instance.itemSlot141 = ItemStack.read(nbt.getCompound("itemSlot141"));
			instance.itemSlot142 = ItemStack.read(nbt.getCompound("itemSlot142"));
			instance.itemSlot143 = ItemStack.read(nbt.getCompound("itemSlot143"));
			instance.itemSlot144 = ItemStack.read(nbt.getCompound("itemSlot144"));
			instance.itemSlot145 = ItemStack.read(nbt.getCompound("itemSlot145"));
			instance.itemSlot146 = ItemStack.read(nbt.getCompound("itemSlot146"));
			instance.itemSlot147 = ItemStack.read(nbt.getCompound("itemSlot147"));
			instance.itemSlot148 = ItemStack.read(nbt.getCompound("itemSlot148"));
			instance.itemSlot149 = ItemStack.read(nbt.getCompound("itemSlot149"));
			instance.itemSlot150 = ItemStack.read(nbt.getCompound("itemSlot150"));
			instance.itemSlot151 = ItemStack.read(nbt.getCompound("itemSlot151"));
			instance.itemSlot152 = ItemStack.read(nbt.getCompound("itemSlot152"));
			instance.itemSlot153 = ItemStack.read(nbt.getCompound("itemSlot153"));
			instance.itemSlot154 = ItemStack.read(nbt.getCompound("itemSlot154"));
			instance.itemSlot155 = ItemStack.read(nbt.getCompound("itemSlot155"));
			instance.itemSlot156 = ItemStack.read(nbt.getCompound("itemSlot156"));
			instance.itemSlot157 = ItemStack.read(nbt.getCompound("itemSlot157"));
			instance.itemSlot158 = ItemStack.read(nbt.getCompound("itemSlot158"));
			instance.itemSlot159 = ItemStack.read(nbt.getCompound("itemSlot159"));
			instance.itemSlot160 = ItemStack.read(nbt.getCompound("itemSlot160"));
			instance.itemSlot161 = ItemStack.read(nbt.getCompound("itemSlot161"));
			instance.itemSlot162 = ItemStack.read(nbt.getCompound("itemSlot162"));
			instance.itemSlot163 = ItemStack.read(nbt.getCompound("itemSlot163"));
			instance.itemSlot164 = ItemStack.read(nbt.getCompound("itemSlot164"));
			instance.itemSlot165 = ItemStack.read(nbt.getCompound("itemSlot165"));
			instance.itemSlot166 = ItemStack.read(nbt.getCompound("itemSlot166"));
			instance.itemSlot167 = ItemStack.read(nbt.getCompound("itemSlot167"));
			instance.itemSlot168 = ItemStack.read(nbt.getCompound("itemSlot168"));
			instance.itemSlot169 = ItemStack.read(nbt.getCompound("itemSlot169"));
			instance.itemSlot170 = ItemStack.read(nbt.getCompound("itemSlot170"));
			instance.itemSlot171 = ItemStack.read(nbt.getCompound("itemSlot171"));
			instance.itemSlot172 = ItemStack.read(nbt.getCompound("itemSlot172"));
			instance.itemSlot173 = ItemStack.read(nbt.getCompound("itemSlot173"));
			instance.itemSlot174 = ItemStack.read(nbt.getCompound("itemSlot174"));
			instance.itemSlot175 = ItemStack.read(nbt.getCompound("itemSlot175"));
			instance.itemSlot176 = ItemStack.read(nbt.getCompound("itemSlot176"));
			instance.itemSlot177 = ItemStack.read(nbt.getCompound("itemSlot177"));
			instance.itemSlot178 = ItemStack.read(nbt.getCompound("itemSlot178"));
			instance.itemSlot179 = ItemStack.read(nbt.getCompound("itemSlot179"));
			instance.itemSlot180 = ItemStack.read(nbt.getCompound("itemSlot180"));
			instance.itemSlot181 = ItemStack.read(nbt.getCompound("itemSlot181"));
			instance.itemSlot182 = ItemStack.read(nbt.getCompound("itemSlot182"));
			instance.itemSlot183 = ItemStack.read(nbt.getCompound("itemSlot183"));
			instance.itemSlot184 = ItemStack.read(nbt.getCompound("itemSlot184"));
			instance.itemSlot185 = ItemStack.read(nbt.getCompound("itemSlot185"));
			instance.itemSlot186 = ItemStack.read(nbt.getCompound("itemSlot186"));
			instance.itemSlot187 = ItemStack.read(nbt.getCompound("itemSlot187"));
			instance.itemSlot188 = ItemStack.read(nbt.getCompound("itemSlot188"));
			instance.itemSlot189 = ItemStack.read(nbt.getCompound("itemSlot189"));
			instance.itemSlot190 = ItemStack.read(nbt.getCompound("itemSlot190"));
			instance.itemSlot191 = ItemStack.read(nbt.getCompound("itemSlot191"));
			instance.itemSlot192 = ItemStack.read(nbt.getCompound("itemSlot192"));
			instance.itemSlot193 = ItemStack.read(nbt.getCompound("itemSlot193"));
			instance.itemSlot194 = ItemStack.read(nbt.getCompound("itemSlot194"));
			instance.itemSlot195 = ItemStack.read(nbt.getCompound("itemSlot195"));
			instance.itemSlot196 = ItemStack.read(nbt.getCompound("itemSlot196"));
			instance.itemSlot197 = ItemStack.read(nbt.getCompound("itemSlot197"));
			instance.itemSlot198 = ItemStack.read(nbt.getCompound("itemSlot198"));
			instance.itemSlot199 = ItemStack.read(nbt.getCompound("itemSlot199"));
			instance.itemSlot200 = ItemStack.read(nbt.getCompound("itemSlot200"));
			instance.itemSlot201 = ItemStack.read(nbt.getCompound("itemSlot201"));
			instance.itemSlot202 = ItemStack.read(nbt.getCompound("itemSlot202"));
			instance.itemSlot203 = ItemStack.read(nbt.getCompound("itemSlot203"));
			instance.itemSlot204 = ItemStack.read(nbt.getCompound("itemSlot204"));
			instance.itemSlot205 = ItemStack.read(nbt.getCompound("itemSlot205"));
			instance.itemSlot206 = ItemStack.read(nbt.getCompound("itemSlot206"));
			instance.itemSlot207 = ItemStack.read(nbt.getCompound("itemSlot207"));
			instance.itemSlot208 = ItemStack.read(nbt.getCompound("itemSlot208"));
			instance.itemSlot209 = ItemStack.read(nbt.getCompound("itemSlot209"));
			instance.itemSlot210 = ItemStack.read(nbt.getCompound("itemSlot210"));
			instance.itemSlot211 = ItemStack.read(nbt.getCompound("itemSlot211"));
			instance.itemSlot212 = ItemStack.read(nbt.getCompound("itemSlot212"));
			instance.itemSlot213 = ItemStack.read(nbt.getCompound("itemSlot213"));
			instance.itemSlot214 = ItemStack.read(nbt.getCompound("itemSlot214"));
			instance.itemSlot215 = ItemStack.read(nbt.getCompound("itemSlot215"));
			instance.itemSlot216 = ItemStack.read(nbt.getCompound("itemSlot216"));
			instance.itemSlot217 = ItemStack.read(nbt.getCompound("itemSlot217"));
			instance.itemSlot219 = ItemStack.read(nbt.getCompound("itemSlot219"));
			instance.itemSlot220 = ItemStack.read(nbt.getCompound("itemSlot220"));
			instance.itemSlot221 = ItemStack.read(nbt.getCompound("itemSlot221"));
			instance.itemSlot222 = ItemStack.read(nbt.getCompound("itemSlot222"));
			instance.itemSlot223 = ItemStack.read(nbt.getCompound("itemSlot223"));
			instance.itemSlot218 = ItemStack.read(nbt.getCompound("itemSlot218"));
			instance.itemSlot224 = ItemStack.read(nbt.getCompound("itemSlot224"));
			instance.itemSlot225 = ItemStack.read(nbt.getCompound("itemSlot225"));
			instance.itemSlot226 = ItemStack.read(nbt.getCompound("itemSlot226"));
			instance.itemSlot227 = ItemStack.read(nbt.getCompound("itemSlot227"));
			instance.itemSlot228 = ItemStack.read(nbt.getCompound("itemSlot228"));
			instance.itemSlot229 = ItemStack.read(nbt.getCompound("itemSlot229"));
			instance.itemSlot230 = ItemStack.read(nbt.getCompound("itemSlot230"));
			instance.itemSlot231 = ItemStack.read(nbt.getCompound("itemSlot231"));
			instance.itemSlot232 = ItemStack.read(nbt.getCompound("itemSlot232"));
			instance.itemSlot233 = ItemStack.read(nbt.getCompound("itemSlot233"));
			instance.itemSlot234 = ItemStack.read(nbt.getCompound("itemSlot234"));
			instance.itemSlot235 = ItemStack.read(nbt.getCompound("itemSlot235"));
			instance.itemSlot236 = ItemStack.read(nbt.getCompound("itemSlot236"));
			instance.itemSlot237 = ItemStack.read(nbt.getCompound("itemSlot237"));
			instance.itemSlot238 = ItemStack.read(nbt.getCompound("itemSlot238"));
			instance.itemSlot239 = ItemStack.read(nbt.getCompound("itemSlot239"));
			instance.itemSlot241 = ItemStack.read(nbt.getCompound("itemSlot241"));
			instance.itemSlot240 = ItemStack.read(nbt.getCompound("itemSlot240"));
			instance.itemSlot242 = ItemStack.read(nbt.getCompound("itemSlot242"));
			instance.itemSlot243 = ItemStack.read(nbt.getCompound("itemSlot243"));
			instance.itemSlot244 = ItemStack.read(nbt.getCompound("itemSlot244"));
			instance.itemSlot245 = ItemStack.read(nbt.getCompound("itemSlot245"));
		}
	}

	public static class PlayerVariables {
		public ItemStack itemSlot0 = ItemStack.EMPTY;
		public double itemSlot0quantity = 0;
		public ItemStack itemSlot1 = ItemStack.EMPTY;
		public double itemSlot1quantity = 0;
		public ItemStack itemSlot2 = ItemStack.EMPTY;
		public ItemStack itemSlot3 = ItemStack.EMPTY;
		public ItemStack itemSlot4 = ItemStack.EMPTY;
		public ItemStack itemSlot5 = ItemStack.EMPTY;
		public ItemStack itemSlot6 = ItemStack.EMPTY;
		public ItemStack itemSlot7 = ItemStack.EMPTY;
		public ItemStack itemSlot8 = ItemStack.EMPTY;
		public ItemStack itemSlot9 = ItemStack.EMPTY;
		public ItemStack itemSlot10 = ItemStack.EMPTY;
		public ItemStack itemSlot11 = ItemStack.EMPTY;
		public ItemStack itemSlot12 = ItemStack.EMPTY;
		public ItemStack itemSlot13 = ItemStack.EMPTY;
		public ItemStack itemSlot14 = ItemStack.EMPTY;
		public ItemStack itemSlot15 = ItemStack.EMPTY;
		public ItemStack itemSlot16 = ItemStack.EMPTY;
		public ItemStack itemSlot17 = ItemStack.EMPTY;
		public ItemStack itemSlot18 = ItemStack.EMPTY;
		public ItemStack itemSlot19 = ItemStack.EMPTY;
		public ItemStack itemSlot20 = ItemStack.EMPTY;
		public ItemStack itemSlot21 = ItemStack.EMPTY;
		public ItemStack itemSlot22 = ItemStack.EMPTY;
		public ItemStack itemSlot23 = ItemStack.EMPTY;
		public ItemStack itemSlot24 = ItemStack.EMPTY;
		public ItemStack itemSlot25 = ItemStack.EMPTY;
		public ItemStack itemSlot26 = ItemStack.EMPTY;
		public ItemStack itemSlot27 = ItemStack.EMPTY;
		public ItemStack itemSlot28 = ItemStack.EMPTY;
		public ItemStack itemSlot29 = ItemStack.EMPTY;
		public ItemStack itemSlot30 = ItemStack.EMPTY;
		public ItemStack itemSlot31 = ItemStack.EMPTY;
		public ItemStack itemSlot32 = ItemStack.EMPTY;
		public ItemStack itemSlot33 = ItemStack.EMPTY;
		public ItemStack itemSlot34 = ItemStack.EMPTY;
		public ItemStack itemSlot35 = ItemStack.EMPTY;
		public ItemStack itemSlot36 = ItemStack.EMPTY;
		public ItemStack itemSlot37 = ItemStack.EMPTY;
		public ItemStack itemSlot38 = ItemStack.EMPTY;
		public ItemStack itemSlot39 = ItemStack.EMPTY;
		public ItemStack itemSlot40 = ItemStack.EMPTY;
		public ItemStack itemSlot41 = ItemStack.EMPTY;
		public ItemStack itemSlot42 = ItemStack.EMPTY;
		public ItemStack itemSlot43 = ItemStack.EMPTY;
		public ItemStack itemSlot44 = ItemStack.EMPTY;
		public ItemStack itemSlot45 = ItemStack.EMPTY;
		public ItemStack itemSlot46 = ItemStack.EMPTY;
		public ItemStack itemSlot47 = ItemStack.EMPTY;
		public ItemStack itemSlot48 = ItemStack.EMPTY;
		public ItemStack itemSlot49 = ItemStack.EMPTY;
		public ItemStack itemSlot50 = ItemStack.EMPTY;
		public ItemStack itemSlot51 = ItemStack.EMPTY;
		public ItemStack itemSlot52 = ItemStack.EMPTY;
		public ItemStack itemSlot53 = ItemStack.EMPTY;
		public ItemStack itemSlot54 = ItemStack.EMPTY;
		public ItemStack itemSlot55 = ItemStack.EMPTY;
		public ItemStack itemSlot56 = ItemStack.EMPTY;
		public ItemStack itemSlot57 = ItemStack.EMPTY;
		public ItemStack itemSlot58 = ItemStack.EMPTY;
		public ItemStack itemSlot59 = ItemStack.EMPTY;
		public ItemStack itemSlot60 = ItemStack.EMPTY;
		public ItemStack itemSlot61 = ItemStack.EMPTY;
		public ItemStack itemSlot62 = ItemStack.EMPTY;
		public ItemStack itemSlot63 = ItemStack.EMPTY;
		public ItemStack itemSlot64 = ItemStack.EMPTY;
		public ItemStack itemSlot65 = ItemStack.EMPTY;
		public ItemStack itemSlot66 = ItemStack.EMPTY;
		public ItemStack itemSlot67 = ItemStack.EMPTY;
		public ItemStack itemSlot68 = ItemStack.EMPTY;
		public ItemStack itemSlot69 = ItemStack.EMPTY;
		public ItemStack itemSlot70 = ItemStack.EMPTY;
		public ItemStack itemSlot71 = ItemStack.EMPTY;
		public ItemStack itemSlot72 = ItemStack.EMPTY;
		public ItemStack itemSlot73 = ItemStack.EMPTY;
		public ItemStack itemSlot74 = ItemStack.EMPTY;
		public ItemStack itemSlot75 = ItemStack.EMPTY;
		public ItemStack itemSlot77 = ItemStack.EMPTY;
		public ItemStack itemSlot78 = ItemStack.EMPTY;
		public ItemStack itemSlot79 = ItemStack.EMPTY;
		public ItemStack itemSlot80 = ItemStack.EMPTY;
		public ItemStack itemSlot81 = ItemStack.EMPTY;
		public ItemStack itemSlot82 = ItemStack.EMPTY;
		public ItemStack itemSlot83 = ItemStack.EMPTY;
		public ItemStack itemSlot84 = ItemStack.EMPTY;
		public ItemStack itemSlot85 = ItemStack.EMPTY;
		public ItemStack itemSlot86 = ItemStack.EMPTY;
		public ItemStack itemSlot87 = ItemStack.EMPTY;
		public ItemStack itemSlot88 = ItemStack.EMPTY;
		public ItemStack itemSlot89 = ItemStack.EMPTY;
		public ItemStack itemSlot91 = ItemStack.EMPTY;
		public ItemStack itemSlot92 = ItemStack.EMPTY;
		public ItemStack itemSlot93 = ItemStack.EMPTY;
		public ItemStack itemSlot94 = ItemStack.EMPTY;
		public ItemStack itemSlot95 = ItemStack.EMPTY;
		public ItemStack itemSlot96 = ItemStack.EMPTY;
		public ItemStack itemSlot97 = ItemStack.EMPTY;
		public ItemStack itemSlot98 = ItemStack.EMPTY;
		public ItemStack itemSlot99 = ItemStack.EMPTY;
		public ItemStack itemSlot100 = ItemStack.EMPTY;
		public ItemStack itemSlot101 = ItemStack.EMPTY;
		public ItemStack itemSlot102 = ItemStack.EMPTY;
		public ItemStack itemSlot103 = ItemStack.EMPTY;
		public ItemStack itemSlot104 = ItemStack.EMPTY;
		public ItemStack itemSlot105 = ItemStack.EMPTY;
		public ItemStack itemSlot106 = ItemStack.EMPTY;
		public ItemStack itemSlot107 = ItemStack.EMPTY;
		public ItemStack itemSlot108 = ItemStack.EMPTY;
		public ItemStack itemSlot109 = ItemStack.EMPTY;
		public ItemStack itemSlot110 = ItemStack.EMPTY;
		public ItemStack itemSlot111 = ItemStack.EMPTY;
		public ItemStack itemSlot112 = ItemStack.EMPTY;
		public ItemStack itemSlot113 = ItemStack.EMPTY;
		public ItemStack itemSlot114 = ItemStack.EMPTY;
		public ItemStack itemSlot115 = ItemStack.EMPTY;
		public ItemStack itemSlot116 = ItemStack.EMPTY;
		public ItemStack itemSlot117 = ItemStack.EMPTY;
		public ItemStack itemSlot118 = ItemStack.EMPTY;
		public ItemStack itemSlot119 = ItemStack.EMPTY;
		public ItemStack itemSlot120 = ItemStack.EMPTY;
		public ItemStack itemSlot121 = ItemStack.EMPTY;
		public ItemStack itemSlot122 = ItemStack.EMPTY;
		public ItemStack itemSlot123 = ItemStack.EMPTY;
		public ItemStack itemSlot124 = ItemStack.EMPTY;
		public ItemStack itemSlot125 = ItemStack.EMPTY;
		public ItemStack itemSlot126 = ItemStack.EMPTY;
		public ItemStack itemSlot127 = ItemStack.EMPTY;
		public ItemStack itemSlot128 = ItemStack.EMPTY;
		public ItemStack itemSlot129 = ItemStack.EMPTY;
		public ItemStack itemSlot130 = ItemStack.EMPTY;
		public ItemStack itemSlot131 = ItemStack.EMPTY;
		public ItemStack itemSlot132 = ItemStack.EMPTY;
		public ItemStack itemSlot133 = ItemStack.EMPTY;
		public ItemStack itemSlot134 = ItemStack.EMPTY;
		public ItemStack itemSlot135 = ItemStack.EMPTY;
		public ItemStack itemSlot136 = ItemStack.EMPTY;
		public ItemStack itemSlot137 = ItemStack.EMPTY;
		public ItemStack itemSlot138 = ItemStack.EMPTY;
		public ItemStack itemSlot139 = ItemStack.EMPTY;
		public ItemStack itemSlot140 = ItemStack.EMPTY;
		public ItemStack itemSlot141 = ItemStack.EMPTY;
		public ItemStack itemSlot142 = ItemStack.EMPTY;
		public ItemStack itemSlot143 = ItemStack.EMPTY;
		public ItemStack itemSlot144 = ItemStack.EMPTY;
		public ItemStack itemSlot145 = ItemStack.EMPTY;
		public ItemStack itemSlot146 = ItemStack.EMPTY;
		public ItemStack itemSlot147 = ItemStack.EMPTY;
		public ItemStack itemSlot148 = ItemStack.EMPTY;
		public ItemStack itemSlot149 = ItemStack.EMPTY;
		public ItemStack itemSlot150 = ItemStack.EMPTY;
		public ItemStack itemSlot151 = ItemStack.EMPTY;
		public ItemStack itemSlot152 = ItemStack.EMPTY;
		public ItemStack itemSlot153 = ItemStack.EMPTY;
		public ItemStack itemSlot154 = ItemStack.EMPTY;
		public ItemStack itemSlot155 = ItemStack.EMPTY;
		public ItemStack itemSlot156 = ItemStack.EMPTY;
		public ItemStack itemSlot157 = ItemStack.EMPTY;
		public ItemStack itemSlot158 = ItemStack.EMPTY;
		public ItemStack itemSlot159 = ItemStack.EMPTY;
		public ItemStack itemSlot160 = ItemStack.EMPTY;
		public ItemStack itemSlot161 = ItemStack.EMPTY;
		public ItemStack itemSlot162 = ItemStack.EMPTY;
		public ItemStack itemSlot163 = ItemStack.EMPTY;
		public ItemStack itemSlot164 = ItemStack.EMPTY;
		public ItemStack itemSlot165 = ItemStack.EMPTY;
		public ItemStack itemSlot166 = ItemStack.EMPTY;
		public ItemStack itemSlot167 = ItemStack.EMPTY;
		public ItemStack itemSlot168 = ItemStack.EMPTY;
		public ItemStack itemSlot169 = ItemStack.EMPTY;
		public ItemStack itemSlot170 = ItemStack.EMPTY;
		public ItemStack itemSlot171 = ItemStack.EMPTY;
		public ItemStack itemSlot172 = ItemStack.EMPTY;
		public ItemStack itemSlot173 = ItemStack.EMPTY;
		public ItemStack itemSlot174 = ItemStack.EMPTY;
		public ItemStack itemSlot175 = ItemStack.EMPTY;
		public ItemStack itemSlot176 = ItemStack.EMPTY;
		public ItemStack itemSlot177 = ItemStack.EMPTY;
		public ItemStack itemSlot178 = ItemStack.EMPTY;
		public ItemStack itemSlot179 = ItemStack.EMPTY;
		public ItemStack itemSlot180 = ItemStack.EMPTY;
		public ItemStack itemSlot181 = ItemStack.EMPTY;
		public ItemStack itemSlot182 = ItemStack.EMPTY;
		public ItemStack itemSlot183 = ItemStack.EMPTY;
		public ItemStack itemSlot184 = ItemStack.EMPTY;
		public ItemStack itemSlot185 = ItemStack.EMPTY;
		public ItemStack itemSlot186 = ItemStack.EMPTY;
		public ItemStack itemSlot187 = ItemStack.EMPTY;
		public ItemStack itemSlot188 = ItemStack.EMPTY;
		public ItemStack itemSlot189 = ItemStack.EMPTY;
		public ItemStack itemSlot190 = ItemStack.EMPTY;
		public ItemStack itemSlot191 = ItemStack.EMPTY;
		public ItemStack itemSlot192 = ItemStack.EMPTY;
		public ItemStack itemSlot193 = ItemStack.EMPTY;
		public ItemStack itemSlot194 = ItemStack.EMPTY;
		public ItemStack itemSlot195 = ItemStack.EMPTY;
		public ItemStack itemSlot196 = ItemStack.EMPTY;
		public ItemStack itemSlot197 = ItemStack.EMPTY;
		public ItemStack itemSlot198 = ItemStack.EMPTY;
		public ItemStack itemSlot199 = ItemStack.EMPTY;
		public ItemStack itemSlot200 = ItemStack.EMPTY;
		public ItemStack itemSlot201 = ItemStack.EMPTY;
		public ItemStack itemSlot202 = ItemStack.EMPTY;
		public ItemStack itemSlot203 = ItemStack.EMPTY;
		public ItemStack itemSlot204 = ItemStack.EMPTY;
		public ItemStack itemSlot205 = ItemStack.EMPTY;
		public ItemStack itemSlot206 = ItemStack.EMPTY;
		public ItemStack itemSlot207 = ItemStack.EMPTY;
		public ItemStack itemSlot208 = ItemStack.EMPTY;
		public ItemStack itemSlot209 = ItemStack.EMPTY;
		public ItemStack itemSlot210 = ItemStack.EMPTY;
		public ItemStack itemSlot211 = ItemStack.EMPTY;
		public ItemStack itemSlot212 = ItemStack.EMPTY;
		public ItemStack itemSlot213 = ItemStack.EMPTY;
		public ItemStack itemSlot214 = ItemStack.EMPTY;
		public ItemStack itemSlot215 = ItemStack.EMPTY;
		public ItemStack itemSlot216 = ItemStack.EMPTY;
		public ItemStack itemSlot217 = ItemStack.EMPTY;
		public ItemStack itemSlot219 = ItemStack.EMPTY;
		public ItemStack itemSlot220 = ItemStack.EMPTY;
		public ItemStack itemSlot221 = ItemStack.EMPTY;
		public ItemStack itemSlot222 = ItemStack.EMPTY;
		public ItemStack itemSlot223 = ItemStack.EMPTY;
		public ItemStack itemSlot218 = ItemStack.EMPTY;
		public ItemStack itemSlot224 = ItemStack.EMPTY;
		public ItemStack itemSlot225 = ItemStack.EMPTY;
		public ItemStack itemSlot226 = ItemStack.EMPTY;
		public ItemStack itemSlot227 = ItemStack.EMPTY;
		public ItemStack itemSlot228 = ItemStack.EMPTY;
		public ItemStack itemSlot229 = ItemStack.EMPTY;
		public ItemStack itemSlot230 = ItemStack.EMPTY;
		public ItemStack itemSlot231 = ItemStack.EMPTY;
		public ItemStack itemSlot232 = ItemStack.EMPTY;
		public ItemStack itemSlot233 = ItemStack.EMPTY;
		public ItemStack itemSlot234 = ItemStack.EMPTY;
		public ItemStack itemSlot235 = ItemStack.EMPTY;
		public ItemStack itemSlot236 = ItemStack.EMPTY;
		public ItemStack itemSlot237 = ItemStack.EMPTY;
		public ItemStack itemSlot238 = ItemStack.EMPTY;
		public ItemStack itemSlot239 = ItemStack.EMPTY;
		public ItemStack itemSlot241 = ItemStack.EMPTY;
		public ItemStack itemSlot240 = ItemStack.EMPTY;
		public ItemStack itemSlot242 = ItemStack.EMPTY;
		public ItemStack itemSlot243 = ItemStack.EMPTY;
		public ItemStack itemSlot244 = ItemStack.EMPTY;
		public ItemStack itemSlot245 = ItemStack.EMPTY;

		public void syncPlayerVariables(Entity entity) {
			if (entity instanceof ServerPlayerEntity)
				MinecraftutilitiesMod.PACKET_HANDLER.send(PacketDistributor.PLAYER.with(() -> (ServerPlayerEntity) entity),
						new PlayerVariablesSyncMessage(this));
		}
	}

	@SubscribeEvent
	public void onPlayerLoggedInSyncPlayerVariables(PlayerEvent.PlayerLoggedInEvent event) {
		if (!event.getPlayer().world.isRemote())
			((PlayerVariables) event.getPlayer().getCapability(PLAYER_VARIABLES_CAPABILITY, null).orElse(new PlayerVariables()))
					.syncPlayerVariables(event.getPlayer());
	}

	@SubscribeEvent
	public void onPlayerRespawnedSyncPlayerVariables(PlayerEvent.PlayerRespawnEvent event) {
		if (!event.getPlayer().world.isRemote())
			((PlayerVariables) event.getPlayer().getCapability(PLAYER_VARIABLES_CAPABILITY, null).orElse(new PlayerVariables()))
					.syncPlayerVariables(event.getPlayer());
	}

	@SubscribeEvent
	public void onPlayerChangedDimensionSyncPlayerVariables(PlayerEvent.PlayerChangedDimensionEvent event) {
		if (!event.getPlayer().world.isRemote())
			((PlayerVariables) event.getPlayer().getCapability(PLAYER_VARIABLES_CAPABILITY, null).orElse(new PlayerVariables()))
					.syncPlayerVariables(event.getPlayer());
	}

	@SubscribeEvent
	public void clonePlayer(PlayerEvent.Clone event) {
		PlayerVariables original = ((PlayerVariables) event.getOriginal().getCapability(PLAYER_VARIABLES_CAPABILITY, null)
				.orElse(new PlayerVariables()));
		PlayerVariables clone = ((PlayerVariables) event.getEntity().getCapability(PLAYER_VARIABLES_CAPABILITY, null).orElse(new PlayerVariables()));
		clone.itemSlot0 = original.itemSlot0;
		clone.itemSlot0quantity = original.itemSlot0quantity;
		clone.itemSlot1 = original.itemSlot1;
		clone.itemSlot1quantity = original.itemSlot1quantity;
		clone.itemSlot2 = original.itemSlot2;
		clone.itemSlot3 = original.itemSlot3;
		clone.itemSlot4 = original.itemSlot4;
		clone.itemSlot5 = original.itemSlot5;
		clone.itemSlot6 = original.itemSlot6;
		clone.itemSlot7 = original.itemSlot7;
		clone.itemSlot8 = original.itemSlot8;
		clone.itemSlot9 = original.itemSlot9;
		clone.itemSlot10 = original.itemSlot10;
		clone.itemSlot11 = original.itemSlot11;
		clone.itemSlot12 = original.itemSlot12;
		clone.itemSlot13 = original.itemSlot13;
		clone.itemSlot14 = original.itemSlot14;
		clone.itemSlot15 = original.itemSlot15;
		clone.itemSlot16 = original.itemSlot16;
		clone.itemSlot17 = original.itemSlot17;
		clone.itemSlot18 = original.itemSlot18;
		clone.itemSlot19 = original.itemSlot19;
		clone.itemSlot20 = original.itemSlot20;
		clone.itemSlot21 = original.itemSlot21;
		clone.itemSlot22 = original.itemSlot22;
		clone.itemSlot23 = original.itemSlot23;
		clone.itemSlot24 = original.itemSlot24;
		clone.itemSlot25 = original.itemSlot25;
		clone.itemSlot26 = original.itemSlot26;
		clone.itemSlot27 = original.itemSlot27;
		clone.itemSlot28 = original.itemSlot28;
		clone.itemSlot29 = original.itemSlot29;
		clone.itemSlot30 = original.itemSlot30;
		clone.itemSlot31 = original.itemSlot31;
		clone.itemSlot32 = original.itemSlot32;
		clone.itemSlot33 = original.itemSlot33;
		clone.itemSlot34 = original.itemSlot34;
		clone.itemSlot35 = original.itemSlot35;
		clone.itemSlot36 = original.itemSlot36;
		clone.itemSlot37 = original.itemSlot37;
		clone.itemSlot38 = original.itemSlot38;
		clone.itemSlot39 = original.itemSlot39;
		clone.itemSlot40 = original.itemSlot40;
		clone.itemSlot41 = original.itemSlot41;
		clone.itemSlot42 = original.itemSlot42;
		clone.itemSlot43 = original.itemSlot43;
		clone.itemSlot44 = original.itemSlot44;
		clone.itemSlot45 = original.itemSlot45;
		clone.itemSlot46 = original.itemSlot46;
		clone.itemSlot47 = original.itemSlot47;
		clone.itemSlot48 = original.itemSlot48;
		clone.itemSlot49 = original.itemSlot49;
		clone.itemSlot50 = original.itemSlot50;
		clone.itemSlot51 = original.itemSlot51;
		clone.itemSlot52 = original.itemSlot52;
		clone.itemSlot53 = original.itemSlot53;
		clone.itemSlot54 = original.itemSlot54;
		clone.itemSlot55 = original.itemSlot55;
		clone.itemSlot56 = original.itemSlot56;
		clone.itemSlot57 = original.itemSlot57;
		clone.itemSlot58 = original.itemSlot58;
		clone.itemSlot59 = original.itemSlot59;
		clone.itemSlot60 = original.itemSlot60;
		clone.itemSlot61 = original.itemSlot61;
		clone.itemSlot62 = original.itemSlot62;
		clone.itemSlot63 = original.itemSlot63;
		clone.itemSlot64 = original.itemSlot64;
		clone.itemSlot65 = original.itemSlot65;
		clone.itemSlot66 = original.itemSlot66;
		clone.itemSlot67 = original.itemSlot67;
		clone.itemSlot68 = original.itemSlot68;
		clone.itemSlot69 = original.itemSlot69;
		clone.itemSlot70 = original.itemSlot70;
		clone.itemSlot71 = original.itemSlot71;
		clone.itemSlot72 = original.itemSlot72;
		clone.itemSlot73 = original.itemSlot73;
		clone.itemSlot74 = original.itemSlot74;
		clone.itemSlot75 = original.itemSlot75;
		clone.itemSlot77 = original.itemSlot77;
		clone.itemSlot78 = original.itemSlot78;
		clone.itemSlot79 = original.itemSlot79;
		clone.itemSlot80 = original.itemSlot80;
		clone.itemSlot81 = original.itemSlot81;
		clone.itemSlot82 = original.itemSlot82;
		clone.itemSlot83 = original.itemSlot83;
		clone.itemSlot84 = original.itemSlot84;
		clone.itemSlot85 = original.itemSlot85;
		clone.itemSlot86 = original.itemSlot86;
		clone.itemSlot87 = original.itemSlot87;
		clone.itemSlot88 = original.itemSlot88;
		clone.itemSlot89 = original.itemSlot89;
		clone.itemSlot91 = original.itemSlot91;
		clone.itemSlot92 = original.itemSlot92;
		clone.itemSlot93 = original.itemSlot93;
		clone.itemSlot94 = original.itemSlot94;
		clone.itemSlot95 = original.itemSlot95;
		clone.itemSlot96 = original.itemSlot96;
		clone.itemSlot97 = original.itemSlot97;
		clone.itemSlot98 = original.itemSlot98;
		clone.itemSlot99 = original.itemSlot99;
		clone.itemSlot100 = original.itemSlot100;
		clone.itemSlot101 = original.itemSlot101;
		clone.itemSlot102 = original.itemSlot102;
		clone.itemSlot103 = original.itemSlot103;
		clone.itemSlot104 = original.itemSlot104;
		clone.itemSlot105 = original.itemSlot105;
		clone.itemSlot106 = original.itemSlot106;
		clone.itemSlot107 = original.itemSlot107;
		clone.itemSlot108 = original.itemSlot108;
		clone.itemSlot109 = original.itemSlot109;
		clone.itemSlot110 = original.itemSlot110;
		clone.itemSlot111 = original.itemSlot111;
		clone.itemSlot112 = original.itemSlot112;
		clone.itemSlot113 = original.itemSlot113;
		clone.itemSlot114 = original.itemSlot114;
		clone.itemSlot115 = original.itemSlot115;
		clone.itemSlot116 = original.itemSlot116;
		clone.itemSlot117 = original.itemSlot117;
		clone.itemSlot118 = original.itemSlot118;
		clone.itemSlot119 = original.itemSlot119;
		clone.itemSlot120 = original.itemSlot120;
		clone.itemSlot121 = original.itemSlot121;
		clone.itemSlot122 = original.itemSlot122;
		clone.itemSlot123 = original.itemSlot123;
		clone.itemSlot124 = original.itemSlot124;
		clone.itemSlot125 = original.itemSlot125;
		clone.itemSlot126 = original.itemSlot126;
		clone.itemSlot127 = original.itemSlot127;
		clone.itemSlot128 = original.itemSlot128;
		clone.itemSlot129 = original.itemSlot129;
		clone.itemSlot130 = original.itemSlot130;
		clone.itemSlot131 = original.itemSlot131;
		clone.itemSlot132 = original.itemSlot132;
		clone.itemSlot133 = original.itemSlot133;
		clone.itemSlot134 = original.itemSlot134;
		clone.itemSlot135 = original.itemSlot135;
		clone.itemSlot136 = original.itemSlot136;
		clone.itemSlot137 = original.itemSlot137;
		clone.itemSlot138 = original.itemSlot138;
		clone.itemSlot139 = original.itemSlot139;
		clone.itemSlot140 = original.itemSlot140;
		clone.itemSlot141 = original.itemSlot141;
		clone.itemSlot142 = original.itemSlot142;
		clone.itemSlot143 = original.itemSlot143;
		clone.itemSlot144 = original.itemSlot144;
		clone.itemSlot145 = original.itemSlot145;
		clone.itemSlot146 = original.itemSlot146;
		clone.itemSlot147 = original.itemSlot147;
		clone.itemSlot148 = original.itemSlot148;
		clone.itemSlot149 = original.itemSlot149;
		clone.itemSlot150 = original.itemSlot150;
		clone.itemSlot151 = original.itemSlot151;
		clone.itemSlot152 = original.itemSlot152;
		clone.itemSlot153 = original.itemSlot153;
		clone.itemSlot154 = original.itemSlot154;
		clone.itemSlot155 = original.itemSlot155;
		clone.itemSlot156 = original.itemSlot156;
		clone.itemSlot157 = original.itemSlot157;
		clone.itemSlot158 = original.itemSlot158;
		clone.itemSlot159 = original.itemSlot159;
		clone.itemSlot160 = original.itemSlot160;
		clone.itemSlot161 = original.itemSlot161;
		clone.itemSlot162 = original.itemSlot162;
		clone.itemSlot163 = original.itemSlot163;
		clone.itemSlot164 = original.itemSlot164;
		clone.itemSlot165 = original.itemSlot165;
		clone.itemSlot166 = original.itemSlot166;
		clone.itemSlot167 = original.itemSlot167;
		clone.itemSlot168 = original.itemSlot168;
		clone.itemSlot169 = original.itemSlot169;
		clone.itemSlot170 = original.itemSlot170;
		clone.itemSlot171 = original.itemSlot171;
		clone.itemSlot172 = original.itemSlot172;
		clone.itemSlot173 = original.itemSlot173;
		clone.itemSlot174 = original.itemSlot174;
		clone.itemSlot175 = original.itemSlot175;
		clone.itemSlot176 = original.itemSlot176;
		clone.itemSlot177 = original.itemSlot177;
		clone.itemSlot178 = original.itemSlot178;
		clone.itemSlot179 = original.itemSlot179;
		clone.itemSlot180 = original.itemSlot180;
		clone.itemSlot181 = original.itemSlot181;
		clone.itemSlot182 = original.itemSlot182;
		clone.itemSlot183 = original.itemSlot183;
		clone.itemSlot184 = original.itemSlot184;
		clone.itemSlot185 = original.itemSlot185;
		clone.itemSlot186 = original.itemSlot186;
		clone.itemSlot187 = original.itemSlot187;
		clone.itemSlot188 = original.itemSlot188;
		clone.itemSlot189 = original.itemSlot189;
		clone.itemSlot190 = original.itemSlot190;
		clone.itemSlot191 = original.itemSlot191;
		clone.itemSlot192 = original.itemSlot192;
		clone.itemSlot193 = original.itemSlot193;
		clone.itemSlot194 = original.itemSlot194;
		clone.itemSlot195 = original.itemSlot195;
		clone.itemSlot196 = original.itemSlot196;
		clone.itemSlot197 = original.itemSlot197;
		clone.itemSlot198 = original.itemSlot198;
		clone.itemSlot199 = original.itemSlot199;
		clone.itemSlot200 = original.itemSlot200;
		clone.itemSlot201 = original.itemSlot201;
		clone.itemSlot202 = original.itemSlot202;
		clone.itemSlot203 = original.itemSlot203;
		clone.itemSlot204 = original.itemSlot204;
		clone.itemSlot205 = original.itemSlot205;
		clone.itemSlot206 = original.itemSlot206;
		clone.itemSlot207 = original.itemSlot207;
		clone.itemSlot208 = original.itemSlot208;
		clone.itemSlot209 = original.itemSlot209;
		clone.itemSlot210 = original.itemSlot210;
		clone.itemSlot211 = original.itemSlot211;
		clone.itemSlot212 = original.itemSlot212;
		clone.itemSlot213 = original.itemSlot213;
		clone.itemSlot214 = original.itemSlot214;
		clone.itemSlot215 = original.itemSlot215;
		clone.itemSlot216 = original.itemSlot216;
		clone.itemSlot217 = original.itemSlot217;
		clone.itemSlot219 = original.itemSlot219;
		clone.itemSlot220 = original.itemSlot220;
		clone.itemSlot221 = original.itemSlot221;
		clone.itemSlot222 = original.itemSlot222;
		clone.itemSlot223 = original.itemSlot223;
		clone.itemSlot218 = original.itemSlot218;
		clone.itemSlot224 = original.itemSlot224;
		clone.itemSlot225 = original.itemSlot225;
		clone.itemSlot226 = original.itemSlot226;
		clone.itemSlot227 = original.itemSlot227;
		clone.itemSlot228 = original.itemSlot228;
		clone.itemSlot229 = original.itemSlot229;
		clone.itemSlot230 = original.itemSlot230;
		clone.itemSlot231 = original.itemSlot231;
		clone.itemSlot232 = original.itemSlot232;
		clone.itemSlot233 = original.itemSlot233;
		clone.itemSlot234 = original.itemSlot234;
		clone.itemSlot235 = original.itemSlot235;
		clone.itemSlot236 = original.itemSlot236;
		clone.itemSlot237 = original.itemSlot237;
		clone.itemSlot238 = original.itemSlot238;
		clone.itemSlot239 = original.itemSlot239;
		clone.itemSlot241 = original.itemSlot241;
		clone.itemSlot240 = original.itemSlot240;
		clone.itemSlot242 = original.itemSlot242;
		clone.itemSlot243 = original.itemSlot243;
		clone.itemSlot244 = original.itemSlot244;
		clone.itemSlot245 = original.itemSlot245;
		if (!event.isWasDeath()) {
		}
	}

	public static class PlayerVariablesSyncMessage {
		public PlayerVariables data;

		public PlayerVariablesSyncMessage(PacketBuffer buffer) {
			this.data = new PlayerVariables();
			new PlayerVariablesStorage().readNBT(null, this.data, null, buffer.readCompoundTag());
		}

		public PlayerVariablesSyncMessage(PlayerVariables data) {
			this.data = data;
		}

		public static void buffer(PlayerVariablesSyncMessage message, PacketBuffer buffer) {
			buffer.writeCompoundTag((CompoundNBT) new PlayerVariablesStorage().writeNBT(null, message.data, null));
		}

		public static void handler(PlayerVariablesSyncMessage message, Supplier<NetworkEvent.Context> contextSupplier) {
			NetworkEvent.Context context = contextSupplier.get();
			context.enqueueWork(() -> {
				if (!context.getDirection().getReceptionSide().isServer()) {
					PlayerVariables variables = ((PlayerVariables) Minecraft.getInstance().player.getCapability(PLAYER_VARIABLES_CAPABILITY, null)
							.orElse(new PlayerVariables()));
					variables.itemSlot0 = message.data.itemSlot0;
					variables.itemSlot0quantity = message.data.itemSlot0quantity;
					variables.itemSlot1 = message.data.itemSlot1;
					variables.itemSlot1quantity = message.data.itemSlot1quantity;
					variables.itemSlot2 = message.data.itemSlot2;
					variables.itemSlot3 = message.data.itemSlot3;
					variables.itemSlot4 = message.data.itemSlot4;
					variables.itemSlot5 = message.data.itemSlot5;
					variables.itemSlot6 = message.data.itemSlot6;
					variables.itemSlot7 = message.data.itemSlot7;
					variables.itemSlot8 = message.data.itemSlot8;
					variables.itemSlot9 = message.data.itemSlot9;
					variables.itemSlot10 = message.data.itemSlot10;
					variables.itemSlot11 = message.data.itemSlot11;
					variables.itemSlot12 = message.data.itemSlot12;
					variables.itemSlot13 = message.data.itemSlot13;
					variables.itemSlot14 = message.data.itemSlot14;
					variables.itemSlot15 = message.data.itemSlot15;
					variables.itemSlot16 = message.data.itemSlot16;
					variables.itemSlot17 = message.data.itemSlot17;
					variables.itemSlot18 = message.data.itemSlot18;
					variables.itemSlot19 = message.data.itemSlot19;
					variables.itemSlot20 = message.data.itemSlot20;
					variables.itemSlot21 = message.data.itemSlot21;
					variables.itemSlot22 = message.data.itemSlot22;
					variables.itemSlot23 = message.data.itemSlot23;
					variables.itemSlot24 = message.data.itemSlot24;
					variables.itemSlot25 = message.data.itemSlot25;
					variables.itemSlot26 = message.data.itemSlot26;
					variables.itemSlot27 = message.data.itemSlot27;
					variables.itemSlot28 = message.data.itemSlot28;
					variables.itemSlot29 = message.data.itemSlot29;
					variables.itemSlot30 = message.data.itemSlot30;
					variables.itemSlot31 = message.data.itemSlot31;
					variables.itemSlot32 = message.data.itemSlot32;
					variables.itemSlot33 = message.data.itemSlot33;
					variables.itemSlot34 = message.data.itemSlot34;
					variables.itemSlot35 = message.data.itemSlot35;
					variables.itemSlot36 = message.data.itemSlot36;
					variables.itemSlot37 = message.data.itemSlot37;
					variables.itemSlot38 = message.data.itemSlot38;
					variables.itemSlot39 = message.data.itemSlot39;
					variables.itemSlot40 = message.data.itemSlot40;
					variables.itemSlot41 = message.data.itemSlot41;
					variables.itemSlot42 = message.data.itemSlot42;
					variables.itemSlot43 = message.data.itemSlot43;
					variables.itemSlot44 = message.data.itemSlot44;
					variables.itemSlot45 = message.data.itemSlot45;
					variables.itemSlot46 = message.data.itemSlot46;
					variables.itemSlot47 = message.data.itemSlot47;
					variables.itemSlot48 = message.data.itemSlot48;
					variables.itemSlot49 = message.data.itemSlot49;
					variables.itemSlot50 = message.data.itemSlot50;
					variables.itemSlot51 = message.data.itemSlot51;
					variables.itemSlot52 = message.data.itemSlot52;
					variables.itemSlot53 = message.data.itemSlot53;
					variables.itemSlot54 = message.data.itemSlot54;
					variables.itemSlot55 = message.data.itemSlot55;
					variables.itemSlot56 = message.data.itemSlot56;
					variables.itemSlot57 = message.data.itemSlot57;
					variables.itemSlot58 = message.data.itemSlot58;
					variables.itemSlot59 = message.data.itemSlot59;
					variables.itemSlot60 = message.data.itemSlot60;
					variables.itemSlot61 = message.data.itemSlot61;
					variables.itemSlot62 = message.data.itemSlot62;
					variables.itemSlot63 = message.data.itemSlot63;
					variables.itemSlot64 = message.data.itemSlot64;
					variables.itemSlot65 = message.data.itemSlot65;
					variables.itemSlot66 = message.data.itemSlot66;
					variables.itemSlot67 = message.data.itemSlot67;
					variables.itemSlot68 = message.data.itemSlot68;
					variables.itemSlot69 = message.data.itemSlot69;
					variables.itemSlot70 = message.data.itemSlot70;
					variables.itemSlot71 = message.data.itemSlot71;
					variables.itemSlot72 = message.data.itemSlot72;
					variables.itemSlot73 = message.data.itemSlot73;
					variables.itemSlot74 = message.data.itemSlot74;
					variables.itemSlot75 = message.data.itemSlot75;
					variables.itemSlot77 = message.data.itemSlot77;
					variables.itemSlot78 = message.data.itemSlot78;
					variables.itemSlot79 = message.data.itemSlot79;
					variables.itemSlot80 = message.data.itemSlot80;
					variables.itemSlot81 = message.data.itemSlot81;
					variables.itemSlot82 = message.data.itemSlot82;
					variables.itemSlot83 = message.data.itemSlot83;
					variables.itemSlot84 = message.data.itemSlot84;
					variables.itemSlot85 = message.data.itemSlot85;
					variables.itemSlot86 = message.data.itemSlot86;
					variables.itemSlot87 = message.data.itemSlot87;
					variables.itemSlot88 = message.data.itemSlot88;
					variables.itemSlot89 = message.data.itemSlot89;
					variables.itemSlot91 = message.data.itemSlot91;
					variables.itemSlot92 = message.data.itemSlot92;
					variables.itemSlot93 = message.data.itemSlot93;
					variables.itemSlot94 = message.data.itemSlot94;
					variables.itemSlot95 = message.data.itemSlot95;
					variables.itemSlot96 = message.data.itemSlot96;
					variables.itemSlot97 = message.data.itemSlot97;
					variables.itemSlot98 = message.data.itemSlot98;
					variables.itemSlot99 = message.data.itemSlot99;
					variables.itemSlot100 = message.data.itemSlot100;
					variables.itemSlot101 = message.data.itemSlot101;
					variables.itemSlot102 = message.data.itemSlot102;
					variables.itemSlot103 = message.data.itemSlot103;
					variables.itemSlot104 = message.data.itemSlot104;
					variables.itemSlot105 = message.data.itemSlot105;
					variables.itemSlot106 = message.data.itemSlot106;
					variables.itemSlot107 = message.data.itemSlot107;
					variables.itemSlot108 = message.data.itemSlot108;
					variables.itemSlot109 = message.data.itemSlot109;
					variables.itemSlot110 = message.data.itemSlot110;
					variables.itemSlot111 = message.data.itemSlot111;
					variables.itemSlot112 = message.data.itemSlot112;
					variables.itemSlot113 = message.data.itemSlot113;
					variables.itemSlot114 = message.data.itemSlot114;
					variables.itemSlot115 = message.data.itemSlot115;
					variables.itemSlot116 = message.data.itemSlot116;
					variables.itemSlot117 = message.data.itemSlot117;
					variables.itemSlot118 = message.data.itemSlot118;
					variables.itemSlot119 = message.data.itemSlot119;
					variables.itemSlot120 = message.data.itemSlot120;
					variables.itemSlot121 = message.data.itemSlot121;
					variables.itemSlot122 = message.data.itemSlot122;
					variables.itemSlot123 = message.data.itemSlot123;
					variables.itemSlot124 = message.data.itemSlot124;
					variables.itemSlot125 = message.data.itemSlot125;
					variables.itemSlot126 = message.data.itemSlot126;
					variables.itemSlot127 = message.data.itemSlot127;
					variables.itemSlot128 = message.data.itemSlot128;
					variables.itemSlot129 = message.data.itemSlot129;
					variables.itemSlot130 = message.data.itemSlot130;
					variables.itemSlot131 = message.data.itemSlot131;
					variables.itemSlot132 = message.data.itemSlot132;
					variables.itemSlot133 = message.data.itemSlot133;
					variables.itemSlot134 = message.data.itemSlot134;
					variables.itemSlot135 = message.data.itemSlot135;
					variables.itemSlot136 = message.data.itemSlot136;
					variables.itemSlot137 = message.data.itemSlot137;
					variables.itemSlot138 = message.data.itemSlot138;
					variables.itemSlot139 = message.data.itemSlot139;
					variables.itemSlot140 = message.data.itemSlot140;
					variables.itemSlot141 = message.data.itemSlot141;
					variables.itemSlot142 = message.data.itemSlot142;
					variables.itemSlot143 = message.data.itemSlot143;
					variables.itemSlot144 = message.data.itemSlot144;
					variables.itemSlot145 = message.data.itemSlot145;
					variables.itemSlot146 = message.data.itemSlot146;
					variables.itemSlot147 = message.data.itemSlot147;
					variables.itemSlot148 = message.data.itemSlot148;
					variables.itemSlot149 = message.data.itemSlot149;
					variables.itemSlot150 = message.data.itemSlot150;
					variables.itemSlot151 = message.data.itemSlot151;
					variables.itemSlot152 = message.data.itemSlot152;
					variables.itemSlot153 = message.data.itemSlot153;
					variables.itemSlot154 = message.data.itemSlot154;
					variables.itemSlot155 = message.data.itemSlot155;
					variables.itemSlot156 = message.data.itemSlot156;
					variables.itemSlot157 = message.data.itemSlot157;
					variables.itemSlot158 = message.data.itemSlot158;
					variables.itemSlot159 = message.data.itemSlot159;
					variables.itemSlot160 = message.data.itemSlot160;
					variables.itemSlot161 = message.data.itemSlot161;
					variables.itemSlot162 = message.data.itemSlot162;
					variables.itemSlot163 = message.data.itemSlot163;
					variables.itemSlot164 = message.data.itemSlot164;
					variables.itemSlot165 = message.data.itemSlot165;
					variables.itemSlot166 = message.data.itemSlot166;
					variables.itemSlot167 = message.data.itemSlot167;
					variables.itemSlot168 = message.data.itemSlot168;
					variables.itemSlot169 = message.data.itemSlot169;
					variables.itemSlot170 = message.data.itemSlot170;
					variables.itemSlot171 = message.data.itemSlot171;
					variables.itemSlot172 = message.data.itemSlot172;
					variables.itemSlot173 = message.data.itemSlot173;
					variables.itemSlot174 = message.data.itemSlot174;
					variables.itemSlot175 = message.data.itemSlot175;
					variables.itemSlot176 = message.data.itemSlot176;
					variables.itemSlot177 = message.data.itemSlot177;
					variables.itemSlot178 = message.data.itemSlot178;
					variables.itemSlot179 = message.data.itemSlot179;
					variables.itemSlot180 = message.data.itemSlot180;
					variables.itemSlot181 = message.data.itemSlot181;
					variables.itemSlot182 = message.data.itemSlot182;
					variables.itemSlot183 = message.data.itemSlot183;
					variables.itemSlot184 = message.data.itemSlot184;
					variables.itemSlot185 = message.data.itemSlot185;
					variables.itemSlot186 = message.data.itemSlot186;
					variables.itemSlot187 = message.data.itemSlot187;
					variables.itemSlot188 = message.data.itemSlot188;
					variables.itemSlot189 = message.data.itemSlot189;
					variables.itemSlot190 = message.data.itemSlot190;
					variables.itemSlot191 = message.data.itemSlot191;
					variables.itemSlot192 = message.data.itemSlot192;
					variables.itemSlot193 = message.data.itemSlot193;
					variables.itemSlot194 = message.data.itemSlot194;
					variables.itemSlot195 = message.data.itemSlot195;
					variables.itemSlot196 = message.data.itemSlot196;
					variables.itemSlot197 = message.data.itemSlot197;
					variables.itemSlot198 = message.data.itemSlot198;
					variables.itemSlot199 = message.data.itemSlot199;
					variables.itemSlot200 = message.data.itemSlot200;
					variables.itemSlot201 = message.data.itemSlot201;
					variables.itemSlot202 = message.data.itemSlot202;
					variables.itemSlot203 = message.data.itemSlot203;
					variables.itemSlot204 = message.data.itemSlot204;
					variables.itemSlot205 = message.data.itemSlot205;
					variables.itemSlot206 = message.data.itemSlot206;
					variables.itemSlot207 = message.data.itemSlot207;
					variables.itemSlot208 = message.data.itemSlot208;
					variables.itemSlot209 = message.data.itemSlot209;
					variables.itemSlot210 = message.data.itemSlot210;
					variables.itemSlot211 = message.data.itemSlot211;
					variables.itemSlot212 = message.data.itemSlot212;
					variables.itemSlot213 = message.data.itemSlot213;
					variables.itemSlot214 = message.data.itemSlot214;
					variables.itemSlot215 = message.data.itemSlot215;
					variables.itemSlot216 = message.data.itemSlot216;
					variables.itemSlot217 = message.data.itemSlot217;
					variables.itemSlot219 = message.data.itemSlot219;
					variables.itemSlot220 = message.data.itemSlot220;
					variables.itemSlot221 = message.data.itemSlot221;
					variables.itemSlot222 = message.data.itemSlot222;
					variables.itemSlot223 = message.data.itemSlot223;
					variables.itemSlot218 = message.data.itemSlot218;
					variables.itemSlot224 = message.data.itemSlot224;
					variables.itemSlot225 = message.data.itemSlot225;
					variables.itemSlot226 = message.data.itemSlot226;
					variables.itemSlot227 = message.data.itemSlot227;
					variables.itemSlot228 = message.data.itemSlot228;
					variables.itemSlot229 = message.data.itemSlot229;
					variables.itemSlot230 = message.data.itemSlot230;
					variables.itemSlot231 = message.data.itemSlot231;
					variables.itemSlot232 = message.data.itemSlot232;
					variables.itemSlot233 = message.data.itemSlot233;
					variables.itemSlot234 = message.data.itemSlot234;
					variables.itemSlot235 = message.data.itemSlot235;
					variables.itemSlot236 = message.data.itemSlot236;
					variables.itemSlot237 = message.data.itemSlot237;
					variables.itemSlot238 = message.data.itemSlot238;
					variables.itemSlot239 = message.data.itemSlot239;
					variables.itemSlot241 = message.data.itemSlot241;
					variables.itemSlot240 = message.data.itemSlot240;
					variables.itemSlot242 = message.data.itemSlot242;
					variables.itemSlot243 = message.data.itemSlot243;
					variables.itemSlot244 = message.data.itemSlot244;
					variables.itemSlot245 = message.data.itemSlot245;
				}
			});
			context.setPacketHandled(true);
		}
	}
}
